# Generated by Django 4.1.4 on 2023-01-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.IntegerField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Cat', models.CharField(max_length=200)),
            ],
        ),
    ]
