# Generated by Django 4.1.4 on 2023-01-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_my_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('CharityName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=200)),
                ('CharityName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
            ],
        ),
    ]
