# Generated by Django 4.1.4 on 2023-01-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_my_API', '0002_charityregistration_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharityRegistration',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
