# Generated by Django 4.1.4 on 2023-01-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_my_API', '0003_delete_charityregistration_delete_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityRegistration',
            fields=[
                ('CharityId', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('CharityName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CharityName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
            ],
        ),
    ]
