# Generated by Django 4.1.4 on 2023-01-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_my_API', '0004_charityregistration_userregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Price',
        ),
        migrations.AddField(
            model_name='item',
            name='Charity',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
