# Generated by Django 4.1.4 on 2023-01-10 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_my_API', '0009_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='OrderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 5, 7, 58, 627987, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
